spring.application.name=SurfSpace-App
# Configuración básica de OpenAPI (común a todos los entornos)
springdoc.api-docs.path=/api-docs
# Ordena las operaciones por metodo HTTP (GET, POST, PUT, DELETE)
springdoc.swagger-ui.operationsSorter=method
# Ordena las etiquetas (controllers) alfabéticamente
springdoc.swagger-ui.tagsSorter=alpha 
# Habilita el boton - Try it out - para probar endpoints
springdoc.swagger-ui.tryItOutEnabled=true 
# Controla qué tan expandida aparece la documentación al cargar
springdoc.swagger-ui.doc-expansion=none
# Habilita/deshabilita completamente Swagger UI
springdoc.swagger-ui.disable-swagger-default-url=true
# Oculta los endpoints de Spring Boot Actuator
springdoc.show-actuator=false
#solo se documentarán los endpoints que estén bajo /api/....
springdoc.paths-to-match=/api/** 

# Configuración específica para el entorno global
server.port=8080
spring.profiles.active=dev
spring.datasource.url=jdbc:mariadb://localhost:3306/surfspace
spring.datasource.username=adminSS
spring.datasource.password=ss1234





