spring.application.name=SurfSpace-App

# Configuraci?n espec?fica para desarrollo
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Configuraci?n adicional para desarrollo
springdoc.swagger-ui.default-models-expand-depth=1
springdoc.swagger-ui.default-model-expand-depth=1
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.filter=true

# Mostrar m?s detalles en desarrollo
logging.level.org.springdoc=DEBUG

spring.datasource.url=jdbc:mariadb://db:3306/surfspace
spring.datasource.username=adminSS
spring.datasource.password=ss1234

# Configuraci?n de JPA/Hibernate para desarrollo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
